global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: "otel-app-metrics"
    static_configs:
      - targets: ["telemetry-otel-collector:8889"]

  - job_name: "otel-collector-internal"
    static_configs:
      - targets: ["telemetry-otel-collector:8888"]